### ISSUE TITLE
Release a new package version in npm

### ISSUE THREAD

**Issue by marcogrcr** [ispyinternet/cfn-response-promise#2]
Hi:

After #1 was merged to the repository, no new version of the package was published in `npm`. The latest version of [`cfn-response-promise`](https://www.npmjs.com/package/cfn-response-promise) is `1.0.1` and was published on 2018.

Can you release a new version of this package so that it can be consumed via npm?

**Comment by ispyinternet** [comment]
version 1.1.0 published
